from dataclasses import dataclass
from typing import Optional

from app.domain.enums.severity import Severity


@dataclass
class RefactorSuggestion:
    """A recommendation to improve a piece of code, generated by an LLM.

    Suggestions are proposals only: they become patches only after passing
    the safety validation gate.
    """

    id: str
    title: str
    description: str
    file_path: str
    severity: Severity
    rationale: str
    rule_reference: Optional[str] = None
    evidence_scope: Optional[str] = None
    change_anchor: Optional[str] = None
    impacted_symbol: Optional[str] = None
    suggested_code: Optional[str] = None
    is_safe_to_apply: bool = False
